### ISSUE TITLE
Missing package.json file

### ISSUE THREAD

**Issue by fmoliveira** [steveathon/bootstrap-wysiwyg#44]
The repository is missing a package.json file to declare Node.js dependencies.

Although the gulpfile is very small, thus it's easy to know which packages I should install, it's a better practice to have a package.json to declare dependencies.

This will also make it easier for anyone wanting to contribute with the project to get started.

**Comment by RandomlyKnighted** [comment]
As previously discussed in #45 the package.json file already exists in the project. However, this issue could be changed to say that the package.json file needs to be updated. 

I'm currently in the process of recreating the Gulp tasks using Grunt. This will allow us to use our Grunt file with Travis CI since that is what they support. While working on this I'm also in the process of creating a way to automatically update the version numbers of files when it's time to do a release. I'm thinking that I may implement it so that a release can be created via the CLI like so:

```
grunt release                      // Default patch release
grunt release:minor            // Minor release
```

@steveathon @fmoliveira what do you think?

**Comment by fmoliveira** [comment]
@RandomlyKnighted Im my opinion it's always great to have a task to automate the release build. You can run whatever Grunt tasks needed and then use [grunt-version](https://www.npmjs.com/package/grunt-version) to update `bower.json` and `package.json` simultanesouly, avoiding a human error of forgetting to update one of these.

However, I think a new issue should be opened for that task, because the current issue reports a suspect of problem with the lack of package.json, which led me to analise the code to know the project dependendecies. You're working on a new feature for version management, so, they're different issues. I think it'll be better documented that way.

**Comment by RandomlyKnighted** [comment]
Alright, then if you'll close this issue I will open a new one for the feature.

**Comment by fmoliveira** [comment]
Great! ;)
