### ISSUE TITLE
Add image icon issues

### ISSUE THREAD

**Issue by mikael-karlsson** [steveathon/bootstrap-wysiwyg#91]
Hi

When I try to click the icon to add an image, my cursor sometimes changes into a hand, and clicking the icon does nothing, and at other times it works just fine. 

After experimenting a bit, I made an odd discovery. Whenever I approach the icon from above with the mouse, it works just fine, but if I approach the icon from below, or slides it down just to the lower edge of the icon, it stops working. 

That probably isn´t the best way to describe the actual issue, but it is the most consistent way to reproduce it. 

EDIT: Forgot to add, I am using Google Chrome

**Comment by RandomlyKnighted** [comment]
This is a known issue (#86) and PR #68 fixes this problem.

**Comment by mikael-karlsson** [comment]
Yes, I saw those, and thought they would fix my problem, but I tried changing my bower.json file to get the latest version from github, and it still did not work. 

Also that PR(#68) isn´t in the latest release, right?

**Comment by RandomlyKnighted** [comment]
That's probably because the latest from GitHub does not yet include my PR. Try using git pull and pull in the changes from my fork.

All releases have been made off of the master branch. That PR is setup for the master branch.

The 2.0-dev branch that you see is where I've taken the latest release and started refactoring te code. This code has not yet been released.

**Comment by mikael-karlsson** [comment]
Ok, I will try that. 

Thanks for the quick answers =)
